version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
  - dependency-name: kramdown
    versions:
    - 2.3.0
